services:
  client:
    build: ./FRONTEND
    ports:
      - "3000:3000"
    volumes:
      - ./FRONTEND:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  server:
    build: ./BACKEND
    ports:
      - "5000:5000"
    volumes:
      - ./BACKEND:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/mern-crud-auth
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: 